### ISSUE TITLE
Is it work behind CGNAT using TURN and STUN

### ISSUE THREAD

**Issue by xlmnxp** [Disink/WebRTC-Mesh-VPN#1]
I'm behind CGNAT and I cannot pay to VPS or any type of servers.
I see this project when I search for a way to use Google TURN and STUN servers to make P2P Encrypted VPN for users behind NAT

**Comment by Disink** [comment]
yes it is.
This might be suitable for your project.
You can refer to [aiortc](https://github.com/aiortc/aiortc)

**Comment by xlmnxp** [comment]
@Disink it look like it need server in middle
can we use turn server instead of it?

**Comment by Disink** [comment]
No, it can't. It is used to generate SDP.
SDP is text, so you can use other methods to exchange SDP.
You can even use email, google driver... to exchange.

Maybe you can use aiortc first then you will know how it works.

I don’t know your situation, but many VPS and cloud services can be used for free. It should be a better choice to use them.

**Comment by xlmnxp** [comment]
> No, it can't. It is used to generate SDP. SDP is text, so you can use other methods to exchange SDP. You can even use email, google driver... to exchange.
> 
> Maybe you can use aiortc first then you will know how it works.
> 
> I don’t know your situation, but many VPS and cloud services can be used for free. It should be a better choice to use them.

My Idea is to make P2P VPN based on WebRTC and use Google TURN, STUN and ICE 
If we use TURN protocol we will not need any middleware server to relay the packets between WebRTC Peers (exclude TURN which we can use Google TURN)

**Comment by xlmnxp** [comment]
I'm working for the project in nodejs or maybe I will use rust and reach simple goal for now,
I don't know if python will be better?

**Comment by Disink** [comment]
> My Idea is to make P2P VPN based on WebRTC and use Google TURN, STUN and ICE If we use TURN protocol we will not need any middleware server to relay the packets between WebRTC Peers (exclude TURN which we can use Google TURN)

I left this project for a while, so I might be wrong.

Both TURN and STUN need to exchange SDP.

If you cannot get the public IP with STUN, then you will use the TURN server as your public IP. You will use the TURN server to relay packets.

But I haven't actually used TURN so you may be right.

I refer to this video [What are STUN and TURN Servers? ](https://www.youtube.com/watch?v=4dLJmZOcWFc)

**Comment by Disink** [comment]
> I'm working for the project in nodejs or maybe I will use rust and reach simple goal for now, I don't know if python will be better?

Familiar language is better.

**Comment by xlmnxp** [comment]
> > I'm working for the project in nodejs or maybe I will use rust and reach simple goal for now, I don't know if python will be better?
> 
> Familiar language is better.

I tried nodejs but is miss a way to handle tun/tap and network packets decoders/encoders
I search in NPM and Github without found a good library

maybe I will go with rust or python (if you allow me to develop this project)

**Comment by Disink** [comment]
> I tried nodejs but is miss a way to handle tun/tap and network packets decoders/encoders I search in NPM and Github without found a good library
> 
> maybe I will go with rust or python (if you allow me to develop this project)

Maybe rust and python are better than nodejs in this case
I originally wanted to use nodejs to complete this project, but I found that aiortc is simpler

I don’t recommend you to develop this project. I developed this project just for fun, so it’s not well optimized.

VPN is already in the aiortc's example [datachannel-vpn](https://github.com/aiortc/aiortc/tree/main/examples/datachannel-vpn)
It is a much better choice

**Comment by xlmnxp** [comment]
Thank you
